export default {
  id: 'ch10', num: 10, title: 'וידאו: הבסיס',
  subtitle: 'מעבר למצב וידאו, פורמטים, חשיפה בתנועה, Log, הילוך איטי ושמע',
  lessons: [
    {
      id: '10-1', title: 'מעבר לווידאו, כפתור MOVIE וכלל 180°', minutes: 9,
      goal: 'להעביר את המצלמה למצב וידאו, לבחור פורמט וקצב פריימים, ולקבוע תריס שנותן תנועה טבעית.',
      blocks: [
        { t: 'p', html: 'מתחת לגלגל המצבים יש גלגל קטן נוסף: <kbd>Still/Movie/S&Q</kbd>. בסטילס (📷) התפריטים מותאמים לתמונות. בווידאו (🎥) הם מותאמים לסרטים. ב-S&Q מצלמים הילוך איטי או מהיר. כפתור <kbd>MOVIE</kbd> האדום בחלק העליון מתחיל ועוצר הקלטה.' },
        { t: 'parts', view: 'top', show: ['sq-dial', 'mode-dial', 'movie'], caption: 'גלגל Still/Movie/S&Q יושב מתחת לגלגל המצבים. כפתור MOVIE האדום נמצא ליד כפתור הצילום.' },
        { t: 'menu', path: ['MENU', 'Shooting', 'Image Quality/Rec', 'File Format'], value: 'XAVC HS 4K / XAVC S 4K / XAVC S HD / XAVC S-I 4K' },
        { t: 'table', head: ['פורמט', 'מה זה', 'מתי'], rows: [
          ['<kbd>XAVC HS 4K</kbd>', '4K בקודק HEVC: יותר איכות לאותו נפח', 'ברירה טובה לרוב העבודה, אם המחשב מתמודד עם HEVC'],
          ['<kbd>XAVC S 4K</kbd>', '4K ‏(3840×2160), Long GOP', 'תאימות רחבה'],
          ['<kbd>XAVC S HD</kbd>', '1920×1080', 'קבצים קטנים, רשתות חברתיות'],
          ['<kbd>XAVC S-I 4K</kbd>', 'דחיסת Intra, קבצים גדולים', 'עריכה כבדה וצבע'],
        ] },
        { t: 'menu', path: ['MENU', 'Shooting', 'Image Quality/Rec', 'Movie Settings', 'Rec Frame Rate'], value: '24p / 30p / 60p…', note: 'ב-Record Setting בוחרים קצב סיביות ודגימת צבע, למשל 4:2:2 10bit לעריכה.' },
        { t: 'h', text: 'כלל 180 המעלות' },
        { t: 'p', html: 'כדי שתנועה בווידאו תיראה טבעית (מריחה קלה בין פריים לפריים), התריס צריך להיות בערך <b>1 חלקי פעמיים קצב הפריימים</b>: ‏1/50 ב-24p או 25p, ו-1/125 ב-60p. בשמש זה דורש פילטר ND בקוטר 67 מ"מ, כי אחרת גם F22 לא מספיק.' },
        { t: 'diagram', kind: 'shutter' },
        { t: 'sim', scene: 'rapids', preset: { mode: 'S', t: 1 / 1000, iso: 'AUTO' },
          task: { text: 'הדמיית פריים וידאו ב-25p: קבעו תריס לפי כלל 180°, וראו כמה מריחה טבעית יש במים.', checks: [{ t: 'תריס של לפחות 1/60', c: 't>=1/60' }, { t: 'תריס של עד 1/40', c: 't<=1/40' }, { t: 'חשיפה תקינה', c: 'expOk' }] } },
        { t: 'tip', html: 'הקיצור הוותיק: אם מקליטים בלי להעביר את הגלגל לווידאו, לחיצה על MOVIE עדיין מקליטה. אבל אז ההגדרות (ויחס התמונה) הן של מצב הסטילס.' },
        { t: 'quiz', q: 'אתם מקליטים ב-60p. איזה תריס מתאים לכלל 180°?', options: ['1/60', '1/125', '1/500', '1/30'], answer: 1, explain: 'פעמיים 60 זה 120, והתריס הקרוב שזמין הוא 1/125.' },
      ],
    },
    {
      id: '10-2', title: 'Exposure Ctrl Type, Auto Framing ו-Framing Stabilizer', minutes: 8,
      goal: 'לבחור בין P/A/S/M רגיל לבין שליטה גמישה כמו במצלמת קולנוע, ולהכיר את כלי המסגור האוטומטי.',
      blocks: [
        { t: 'menu', path: ['MENU', 'Shooting', 'Shooting Mode', 'Exposure Ctrl Type'], value: 'P/A/S/M Mode (ברירת מחדל) / Flexible Exp. Mode' },
        { t: 'p', html: 'ב-<kbd>Flexible Exp. Mode</kbd> כל אחד משלושת הפרמטרים (צמצם, תריס, ISO) יכול להיות אוטומטי או ידני, בלי תלות בגלגל המצבים. למשל: תריס נעול על 1/50, צמצם ידני F2.8, ו-ISO אוטומטי. המעבר בין Auto ל-Manual נעשה בכפתורים מותאמים (<kbd>L.PressAv Auto/Manual</kbd> וכדומה).' },
        { t: 'parts', view: 'top', show: ['front-dial', 'rear-dial-r'], caption: 'ב-Flexible Exp. Mode החוגות והגלגל משנים את הצמצם, התריס וה-ISO ישירות.' },
        { t: 'warn', html: 'גם ב-Flexible Exp. Mode: אם לוחצים MOVIE כשהגלגל במצב סטילס, ההקלטה משתמשת במצב שבגלגל המצבים.' },
        { t: 'h', text: 'Auto Framing' },
        { t: 'p', html: 'המצלמה חותכת מתוך פריים 4K ועוקבת אחרי הנושא, כאילו יש צלם שמזיז אותה. מתאים למצלמה על חצובה מול דובר. הגדרות: <kbd>Framing Oper. Mode</kbd> (למשל Auto Start) ו-<kbd>Crop Level</kbd> (Large / Medium / Small).' },
        { t: 'menu', path: ['MENU', 'Shooting', 'Shooting Option', 'Auto Framing Settings', 'Auto Framing'], value: 'On' },
        { t: 'h', text: 'Framing Stabilizer' },
        { t: 'p', html: 'הגדרה הפוכה: שומרת את הנושא שעוקבים אחריו באותו מקום בפריים גם כשהמצלמה ביד (<kbd>On: Center</kbd> או <kbd>On: Manual</kbd>). זמינה מקושחה 2.00 ואילך. גם היא חותכת, ולכן עדיף להקליט ב-HD.' },
        { t: 'menu', path: ['MENU', 'Shooting', 'Image Stabilization', 'Framing Stabilizer'], value: 'On' },
        { t: 'quiz', q: 'רוצים תריס קבוע של 1/50, צמצם שאתם בוחרים, וש-ISO יתאים את עצמו לאור. מה הכי נוח?', options: ['מצב A', 'Flexible Exp. Mode עם ISO אוטומטי', 'מצב AUTO', 'S&Q'], answer: 1, explain: 'ב-Flexible Exp. Mode קובעים בנפרד מה ידני ומה אוטומטי, למשל צמצם ותריס ידניים ו-ISO אוטומטי.' },
      ],
    },
    {
      id: '10-3', title: 'Picture Profile, S-Log3 ו-LUT', minutes: 8,
      goal: 'להבין מה זה Log, מתי הוא שווה את המאמץ, ואיך לראות תמונה נורמלית בזמן צילום ב-Log.',
      blocks: [
        { t: 'p', html: 'וידאו רגיל "אופה" את הצבע והניגודיות לתוך הקובץ. <b>Log</b> שומר תמונה שטוחה ואפורה שמכילה טווח דינמי רחב יותר, ואת המראה הסופי יוצרים בעריכה (color grading).' },
        { t: 'menu', path: ['MENU', 'Shooting', 'Image Quality/Rec', 'Log Shooting Setting', 'Log Shooting'], value: 'On (Flexible ISO)' },
        { t: 'menu', path: ['MENU', 'Exposure/Color', 'Color/Tone', 'Select LUT'], value: 's709 / 709(800%) / User1–User16', note: 'LUT מתרגם את תמונת ה-Log למראה צבעוני רגיל. Display LUT מראה אותו רק על המסך, וה-Embed LUT File מטמיע אותו בקובץ (לא זמין בכרטיסי SD/SDHC רגילים).' },
        { t: 'table', head: ['Profile', 'Gamma'], rows: [
          ['<kbd>PP1</kbd>', 'Movie'], ['<kbd>PP2</kbd>', 'Still'], ['<kbd>PP3</kbd> / <kbd>PP4</kbd>', 'ITU709'], ['<kbd>PP5</kbd> / <kbd>PP6</kbd>', 'Cine1 / Cine2'],
          ['<kbd>PP10</kbd>', 'HLG2 (HDR)'], ['<kbd>PP11</kbd>', 'S-Cinetone'], ['<kbd>PPLUT1</kbd>–<kbd>PPLUT4</kbd>', 'LUT משתמש'],
        ] },
        { t: 'diagram', kind: 'histogram' },
        { t: 'tip', html: 'מתחילים? <kbd>PP11</kbd> (S-Cinetone) נותן מראה קולנועי יפה מהמצלמה, בלי עבודת צבע. עוברים ל-S-Log3 רק כשמוכנים לעשות grading.' },
        { t: 'warn', html: 'ב-S-Log3 הרעש בצללים בולט יותר מבגמות אחרות. חשפו מעט בהיר יותר (Zebra עוזר), והורידו בעריכה.' },
        { t: 'parts', view: 'side', show: ['card-slot', 'hdmi'] },
        { t: 'quiz', q: 'מה התפקיד של LUT בזמן צילום ב-S-Log3?', options: ['מגדיל את הרזולוציה', 'מציג (או מטמיע) תרגום של התמונה השטוחה למראה צבעוני רגיל', 'מוריד רעש', 'מייצב את התמונה'], answer: 1, explain: 'ה-LUT ממפה את הצבעים השטוחים של ה-Log לצבעים רגילים, כדי שתוכלו לשפוט חשיפה וצבע בזמן הצילום.' },
      ],
    },
    {
      id: '10-4', title: 'S&Q, Time-lapse ושמע', minutes: 8,
      goal: 'לצלם הילוך איטי ומהיר, Time-lapse, ולחבר מיקרופון ואוזניות.',
      blocks: [
        { t: 'steps', items: [
          'גלגל <kbd>Still/Movie/S&Q</kbd> על <kbd>S&Q</kbd>.',
          'במסך <kbd>Shoot Mode</kbd> בחרו <kbd>S&Q Motion</kbd> או <kbd>Time-lapse</kbd>.',
          '<kbd>MENU</kbd> → <kbd>Shooting</kbd> → <kbd>Image Quality/Rec</kbd> → <kbd>S&Q Settings</kbd> (או <kbd>Time-lapse Settings</kbd>).',
          '<kbd>MOVIE</kbd> להתחלה ולעצירה. אין הקלטת שמע ב-S&Q.',
        ] },
        { t: 'table', head: ['קצב צילום', 'בהקלטה 24p', 'בהקלטה 60p'], rows: [
          ['120fps', 'פי 5 איטי', 'פי 2 איטי'], ['60fps', 'פי 2.5 איטי', 'מהירות רגילה'], ['30fps', 'פי 1.25 איטי', 'פי 2 מהיר'],
          ['8fps', 'פי 3 מהיר', 'פי 7.5 מהיר'], ['1fps', 'פי 24 מהיר', 'פי 60 מהיר'],
        ] },
        { t: 'p', html: '<b>Time-lapse</b>: מרווח של 1 עד 60 שניות בין פריים לפריים (ב-4K עד 5 שניות), וקצב הקלטה של 60p / 50p / 30p / 25p / 24p. המצלמה מקליטה ברצף עד כ-120 דקות ב-HD וכ-90 ב-4K.' },
        { t: 'tip', html: 'Time-lapse של עננים: חצובה, פוקוס ידני (מתג העדשה על MF), WB קבוע ולא AWB, וחשיפה ב-M, כדי שלא יהיו הבהובים בין פריימים.' },
        { t: 'parts', view: 'side', show: ['mic-jack', 'headphone-jack', 'usb-c'], caption: 'שקע מיקרופון ושקע אוזניות 3.5 מ"מ. כשמחברים מיקרופון חיצוני, המיקרופון המובנה כבה אוטומטית.' },
        { t: 'menu', path: ['MENU', 'Shooting', 'Audio Recording', 'Audio Rec Level'], value: '26 (ברירת מחדל)', note: 'Wind Noise Reduct.: Auto. שווה להאזין באוזניות בזמן ההקלטה.' },
        { t: 'quiz', q: 'צילמתם ב-120fps והסרט מוגדר ל-24p. כמה איטי ייראה הסרט?', options: ['פי 2', 'פי 2.5', 'פי 5', 'רגיל'], answer: 2, explain: '120 חלקי 24 שווה 5: כל שנייה אמיתית נמשכת 5 שניות בסרט.' },
      ],
    },
  ],
};
