// Chapter 4 — Focus. Facts: Sony Help Guide ILCE-7CM2 (docs/manuals), lens: SEL2450G_facts.md
export default {
  id: 'ch4', num: 4, title: 'פוקוס', subtitle: 'איך המצלמה מחליטה מה יהיה חד, ואיך אתם לוקחים שליטה',
  lessons: [
    {
      id: '4-1', title: 'AF-S, AF-A ו-AF-C: מתי כל אחד', minutes: 7,
      goal: 'לבחור את מצב הפוקוס לפי מה שהנושא עושה: עומד, אולי זז, או בתנועה רציפה.',
      blocks: [
        { t: 'p', html: 'פוקוס אוטומטי (AF) הוא המנוע הקטן שבתוך העדשה שמזיז את קבוצת העדשות הפנימית עד שהנושא חד. ב-FE 24-50mm F2.8 G זה מנוע ליניארי מהיר ושקט, והעדשה <b>לא משנה את האורך שלה בזמן פוקוס</b> (פוקוס פנימי). אבל מי שמחליט <i>מתי</i> למקד ו<i>האם להמשיך</i> למקד זו המצלמה, לפי <kbd>Focus Mode</kbd>.' },
        { t: 'table', head: ['מצב', 'מה קורה בלחיצה חצי', 'מתי להשתמש'], rows: [
          ['<kbd>AF-S</kbd> Single-shot AF', 'המצלמה ממקדת פעם אחת ונועלת. שומעים צפצוף וריבוע ירוק.', 'נוף, פורטרט של אדם שעומד, פרח, מוצר'],
          ['<kbd>AF-A</kbd> Automatic AF', 'המצלמה מחליטה לבד: נועלת אם הנושא עומד, ממשיכה לעקוב אם הוא זז. ברצף, מהתמונה השנייה עובר ל-AF-C.', 'ילדים, חיות מחמד, כשלא בטוחים'],
          ['<kbd>AF-C</kbd> Continuous AF', 'הפוקוס מתעדכן כל הזמן שהלחיצה חצי מוחזקת. אין צפצוף.', 'אדם שהולך, כלב שרץ, ספורט, ציפורים'],
          ['<kbd>DMF</kbd>', 'AF ואז אפשר לכוונן ביד בטבעת הפוקוס כשהכפתור עדיין לחוץ חצי.', 'מאקרו, פרחים, כשה-AF כמעט צודק'],
          ['<kbd>MF</kbd> Manual Focus', 'אתם מסובבים את טבעת הפוקוס בעדשה.', 'לילה, כוכבים, צילום דרך זכוכית, וידאו מתוכנן'],
        ] },
        { t: 'menu', path: ['MENU', 'Focus', 'AF/MF', 'Focus Mode'], value: 'Single-shot AF / Automatic AF / Continuous AF / DMF / Manual Focus' },
        { t: 'parts', view: 'top', show: ['shutter'], caption: 'כפתור הצילום: לחיצה חצי = פוקוס (וגם מדידת אור), לחיצה מלאה = צילום.' },
        { t: 'h', text: 'איך יודעים שהפוקוס הצליח' },
        { t: 'p', html: 'ב-AF-S מחוון הפוקוס בתחתית המסך דולק והמסגרת הופכת ירוקה. מחוון מהבהב = הנושא לא בפוקוס. ב-AF-C יש מחוון אחר שדולק כשהנושא חד והמצלמה ממשיכה לכוונן לפי התנועה. ב-AF-C גם אין צפצוף.' },
        { t: 'warn', html: 'הטעות הכי נפוצה: AF-S על אדם שהולך לקראתכם. נעלתם על 4 מ\', עד שלחצתם עד הסוף הוא כבר ב-3.6 מ\'. ב-50 מ"מ F2.8 עומק השדה במרחק 3 מ\' הוא רק מ-2.73 עד 3.33 מ\' (60 ס"מ), אז העיניים יוצאות רכות. לנושא שזז: AF-C.' },
        { t: 'pro', html: 'שתי הגדרות שקובעות מה קורה כשהפוקוס עוד לא מושלם: <kbd>Priority Set in AF-S</kbd> ו-<kbd>Priority Set in AF-C</kbd> (MENU → Focus → AF/MF). אפשרויות: <kbd>AF</kbd> (לא מצלם עד שחד), <kbd>Release</kbd> (מצלם מיד), <kbd>Balanced Emphasis</kbd> (איזון). לחיות וספורט כדאי לנסות Balanced Emphasis.' },
        { t: 'sim', scene: 'kyoto', preset: { mode: 'A', N: 2.8, focusMode: 'AF-S', focusArea: 'wide', recog: 'human' }, lock: ['mode', 'N'],
          task: { text: 'האישה הולכת לקראתכם. החליפו ל-AF-C (כפתור Fn → Focus Mode), החזיקו חצי לחיצה ושחררו לצילום. ודאו שהעין חדה.', checks: [
            { t: 'Focus Mode על AF-C', c: 'focusMode==AF-C' }, { t: 'העין בתוך עומק השדה', c: 'eyeSharp' } ] },
          hint: 'ב-AF-C אין צפצוף. המסגרת הירוקה עוקבת אחרי העין כל עוד הלחיצה החצי מוחזקת.' },
        { t: 'quiz', q: 'אתם מצלמים כלב שרץ אליכם בפארק. איזה מצב פוקוס הכי מתאים?', options: ['AF-S', 'AF-C', 'MF', 'DMF'], answer: 1,
          explain: 'AF-C ממשיך לעדכן את הפוקוס כל זמן שהכפתור לחוץ חצי, כך שהמרחק המשתנה של הכלב מתעדכן בכל רגע.' },
      ],
    },
    {
      id: '4-2', title: 'אזורי פוקוס ו-Tracking', minutes: 9,
      goal: 'להגיד למצלמה איפה בפריים לחפש פוקוס, ולגרום לה לעקוב אחרי נושא שזז.',
      blocks: [
        { t: 'p', html: '<kbd>Focus Mode</kbd> אומר <i>מתי</i> למקד. <kbd>Focus Area</kbd> אומר <i>איפה</i>. כשהמצלמה בוחרת לבד (Wide) היא בדרך כלל בוחרת את הדבר הקרוב והבולט, וזה לא תמיד מה שרציתם.' },
        { t: 'diagram', kind: 'af-areas' },
        { t: 'table', head: ['אזור', 'מה הוא עושה', 'דוגמה'], rows: [
          ['<kbd>Wide</kbd>', 'כל המסך. המצלמה בוחרת לבד.', 'צילום מהיר, נושא אחד בולט'],
          ['<kbd>Zone</kbd>', 'אתם בוחרים אזור, המצלמה בוחרת בתוכו.', 'ציפור בשמיים, ספורטאי באזור ידוע'],
          ['<kbd>Center Fix</kbd>', 'רק במרכז. משלבים עם נעילת פוקוס ומסגור מחדש.', 'מי שרגיל לשיטה הקלאסית'],
          ['<kbd>Spot: L / M / S</kbd>', 'נקודה שאתם מזיזים. S הכי קטנה.', 'עין, עלה אחד, פנס מסוים'],
          ['<kbd>Expand Spot</kbd>', 'כמו Spot, ואם לא מצליח משתמש בנקודות סביב.', 'נושא קטן עם קונטרסט חלש'],
          ['<kbd>Tracking</kbd>', 'מתחיל מהאזור שבחרתם ועוקב אחרי הנושא. רק ב-AF-C ורק בסטילס.', 'אדם הולך, רוכב אופניים'],
        ] },
        { t: 'menu', path: ['MENU', 'Focus', 'Focus Area', 'Focus Area'], value: 'Wide / Zone / Center Fix / Spot: L / Spot: M / Spot: S / Expand Spot / Tracking', note: 'ב-Intelligent Auto ו-Scene Selection האזור נעול על Wide.' },
        { t: 'steps', items: [
          'לחצו <kbd>Fn</kbd> ובחרו <kbd>Focus Area</kbd>.',
          'בחרו <kbd>Spot: M</kbd> בעזרת החוגה הקדמית ואשרו במרכז גלגל השליטה.',
          'הזיזו את המסגרת: בלחצני הגלגל, או בנגיעה במסך (Touch Focus).',
          'לחצו חצי על כפתור הצילום. המסגרת נצבעת ירוק על הנקודה שבחרתם.',
        ] },
        { t: 'parts', view: 'rear', show: ['fn', 'control-wheel', 'monitor'], caption: 'Fn פותח את התפריט המהיר. גלגל השליטה מזיז את מסגרת הפוקוס. המסך הוא גם משטח מגע.' },
        { t: 'sim', scene: 'night', preset: { mode: 'A', focal: 50, focusMode: 'AF-S', focusArea: 'wide' },
          task: { text: 'ב-Wide המצלמה בחרה משהו לבד. בחרו Spot: S, געו בפנס הרחוק במסך, וצלמו כשהוא חד.', checks: [
            { t: 'אזור Spot: S', c: 'focusArea==spotS' }, { t: 'חשיפה תקינה', c: 'expOk' } ] },
          hint: 'בנגיעה במסך המסגרת עוברת לנקודה שנגעתם בה. עקבו אחרי פאנל עומק השדה: מרחק הפוקוס משתנה.' },
        { t: 'pro', html: 'כדי לעבור בין אזורים בלי תפריט: הגבילו את הרשימה ב-<kbd>Focus Area Limit</kbd> (MENU → Focus → Focus Area) ושייכו <kbd>Switch Focus Area</kbd> לכפתור. כל לחיצה מחליפה אזור. כדי לעקוב רק בזמן לחיצה: הפונקציה <kbd>Tracking On</kbd> בכפתור מותאם.' },
        { t: 'quiz', q: 'בחרתם Tracking ב-Focus Area אבל האפשרות אפורה. מה הסיבה הסבירה?', options: ['העדשה על MF', 'Focus Mode לא על Continuous AF', 'ISO גבוה מדי', 'הצמצם סגור מדי'], answer: 1,
          explain: 'לפי המדריך, Tracking ב-Focus Area זמין רק כש-Focus Mode על Continuous AF ורק בצילום סטילס.' },
      ],
    },
    {
      id: '4-3', title: 'זיהוי נושא ו-Eye AF', minutes: 8,
      goal: 'לגרום למצלמה למצוא עין של אדם או חיה ולשמור עליה חדה, גם ב-F2.8.',
      blocks: [
        { t: 'p', html: 'ה-α7C II כוללת יחידת עיבוד בינה מלאכותית שמזהה <b>עיניים, ראש וגוף</b>. כשהיא מזהה נושא בתוך אזור הפוקוס או לידו, היא נותנת לו עדיפות. בפורטרט ב-F2.8, ההבדל בין עין חדה לגבה חדה הוא כל ההבדל.' },
        { t: 'table', head: ['Recognition Target', 'מה מזוהה'], rows: [
          ['<kbd>Auto</kbd>', 'המצלמה בוחרת בין הסוגים שסימנתם (קושחה 2.00 ומעלה)'],
          ['<kbd>Human</kbd>', 'בני אדם'], ['<kbd>Animal/Bird</kbd>', 'חיות וציפורים'], ['<kbd>Animal</kbd>', 'חיות'], ['<kbd>Bird</kbd>', 'ציפורים'],
          ['<kbd>Insect</kbd>', 'חרקים'], ['<kbd>Car/Train</kbd>', 'מכוניות ורכבות'], ['<kbd>Airplane</kbd>', 'מטוסים'],
        ] },
        { t: 'menu', path: ['MENU', 'Focus', 'Subject Recognition', 'Recognition Target'], value: 'Human' },
        { t: 'menu', path: ['MENU', 'Focus', 'Subject Recognition', 'Subject Recog in AF'], value: 'On', note: 'ב-Intelligent Auto ההגדרה נעולה על On.' },
        { t: 'menu', path: ['MENU', 'Focus', 'Subject Recognition', 'Right/Left Eye Select'], value: 'Auto / Right Eye / Left Eye', note: 'Right Eye = העין הימנית של הנושא, כלומר זו שבצד שמאל מבחינתכם.' },
        { t: 'tip', html: 'Eye AF עובד יחד עם <kbd>Focus Area</kbd>. אם בחרתם Spot קטן בצד אחד של הפריים והאדם בצד השני, המצלמה לא תחפש אותו שם. לפורטרט: Wide או Zone, או Tracking עם AF-C.' },
        { t: 'sim', scene: 'kyoto', preset: { mode: 'A', N: 2.8, focusMode: 'AF-C', focusArea: 'spotS', recog: 'off' }, lock: ['mode'],
          task: { text: 'זיהוי הנושא כבוי והנקודה קטנה. הדליקו Recognition Target: Human, החזירו את האזור ל-Wide וצלמו עם עין חדה ב-F2.8.', checks: [
            { t: 'צמצם F2.8', c: 'N<=2.8' }, { t: 'העין חדה', c: 'eyeSharp' }, { t: 'חשיפה תקינה', c: 'expOk' } ] } },
        { t: 'sim', scene: 'dog', preset: { mode: 'A', N: 2.8, focusMode: 'AF-C', focusArea: 'wide', recog: 'human' },
          task: { text: 'הזיהוי מוגדר לבני אדם, אז המצלמה לא מוצאת את עין הכלב. שנו ל-Animal/Bird וצלמו.', checks: [
            { t: 'העין של הכלב חדה', c: 'eyeSharp' }, { t: 'חשיפה תקינה', c: 'expOk' } ] } },
        { t: 'pro', html: 'דרך שנייה: לשייך <kbd>Subject Recognition AF</kbd> לכפתור. לחיצה עליו מחפשת נושא בכל המסך, בלי קשר ל-Focus Area, ואם אין נושא היא לא ממקדת בכלל.' },
        { t: 'quiz', q: 'הדלקתם Animal ומצלמים חתול, אבל המצלמה ממקדת על הגדר שלפניו. מה לבדוק קודם?', options: ['איזון לבן', 'שאזור הפוקוס מכסה את החתול', 'שהעדשה על 24 מ"מ', 'Creative Look'], answer: 1,
          explain: 'Subject Recog in AF מעדיף נושא שמזוהה בתוך אזור הפוקוס או סביבו. אם האזור על הגדר, המצלמה ממקדת עליה.' },
      ],
    },
    {
      id: '4-4', title: 'AF-ON ופוקוס בכפתור אחורי', minutes: 6,
      goal: 'להפריד בין פוקוס לצילום, כדי שהפוקוס לא יזוז בכל לחיצה.',
      blocks: [
        { t: 'p', html: 'בברירת המחדל כפתור הצילום עושה שני דברים: חצי = פוקוס, מלא = צילום. צלמים רבים מעדיפים "פוקוס בכפתור אחורי": האגודל ממקד ב-<kbd>AF-ON</kbd>, והאצבע רק מצלמת.' },
        { t: 'parts', view: 'rear', show: ['af-on'], caption: 'כפתור AF-ON בגב המצלמה, מתחת ל-Rear dial L. ברירת המחדל: Tracking On + AF On.' },
        { t: 'p', html: 'בברירת המחדל משויך ל-AF-ON <kbd>Tracking On + AF On</kbd>: כל עוד הוא לחוץ המצלמה ממקדת <b>ועוקבת</b> אחרי הנושא מהאזור שבחרתם.' },
        { t: 'steps', items: [
          'MENU → Focus → AF/MF → <kbd>AF w/ Shutter</kbd> → <kbd>Off</kbd>. עכשיו לחיצה חצי לא ממקדת.',
          'כדי למקד: לחצו <kbd>AF-ON</kbd> באגודל.',
          'נושא עומד: לחצו AF-ON פעם אחת ושחררו. הפוקוס נשאר נעול, ואפשר לצלם כמה תמונות ולמסגר מחדש.',
          'נושא זז: השאירו את AF-ON לחוץ, וצלמו מתי שרוצים.',
        ] },
        { t: 'menu', path: ['MENU', 'Focus', 'AF/MF', 'AF w/ Shutter'], value: 'Off' },
        { t: 'tip', html: 'היתרון הגדול: אפשר להישאר ב-AF-C כל הזמן. לחיצה קצרה על AF-ON מתנהגת כמו AF-S, והחזקה מתנהגת כמו AF-C.' },
        { t: 'pro', html: 'כדי למקד מראש למרחק קבוע (למשל קו סיום), כבו גם <kbd>AF w/ Shutter</kbd> וגם <kbd>Pre-AF</kbd>, מקדו פעם אחת עם AF-ON וחכו.' },
        { t: 'quiz', q: 'כיביתם AF w/ Shutter. מה קורה כשלוחצים חצי על כפתור הצילום?', options: ['המצלמה ממקדת', 'הפוקוס לא זז, אבל מדידת האור עדיין עובדת', 'המצלמה לא מצלמת', 'Eye AF כבה'], answer: 1,
          explain: 'AF w/ Shutter קובע רק אם הלחיצה החצית ממקדת. הצילום והחשיפה ממשיכים כרגיל.' },
      ],
    },
    {
      id: '4-5', title: 'פוקוס ידני, DMF, Peaking והגדלה', minutes: 10,
      goal: 'למקד ביד במדויק עם טבעת הפוקוס של העדשה, ולהשתמש בכלי העזר של המצלמה.',
      blocks: [
        { t: 'p', html: 'לפעמים AF לא יכול: לילה חשוך, דרך חלון, ענפים לפני הנושא, כוכבים. ב-FE 24-50mm F2.8 G טבעת הפוקוס היא הטבעת <b>הקדמית</b>, המחורצת. היא ליניארית: אותו סיבוב תמיד מזיז את אותו מרחק, בלי קשר למהירות הסיבוב. זה נוח לחזור על אותה נקודה.' },
        { t: 'parts', view: 'lens', show: ['focus-ring', 'afmf-switch', 'focus-hold'], caption: 'טבעת הפוקוס בחזית. בצד שמאל: מתג AF/MF וכפתור Focus Hold העגול.' },
        { t: 'h', text: 'שתי דרכים לעבור ל-MF' },
        { t: 'steps', items: [
          'במתג העדשה: הזיזו את מתג <kbd>AF/MF</kbd> ל-MF. <b>מתג העדשה גובר</b> על הגדרת המצלמה.',
          'או במצלמה: MENU → Focus → AF/MF → Focus Mode → <kbd>Manual Focus</kbd>.',
          'לפוקוס אוטומטי צריך <b>גם</b> את המתג בעדשה על AF <b>וגם</b> את המצלמה על מצב AF.',
        ] },
        { t: 'warn', html: 'אם הפוקוס האוטומטי "הפסיק לעבוד", בדקו קודם את מתג AF/MF בצד העדשה. הוא שטוח וקל להזיז אותו בטעות בתיק.' },
        { t: 'h', text: 'כלי עזר' },
        { t: 'table', head: ['כלי', 'מה הוא עושה', 'איפה'], rows: [
          ['<kbd>Peaking Display</kbd>', 'צובע קווי מתאר של אזורים חדים. רמות: High / Mid / Low. צבעים: Red / Yellow / Blue / White.', 'MENU → Focus → Peaking Display'],
          ['<kbd>Auto Magnifier in MF</kbd>', 'מגדיל את התמונה אוטומטית כשמסובבים את הטבעת. לחיצה במרכז הגלגל מגדילה עוד.', 'MENU → Focus → Focus Assistant'],
          ['<kbd>Focus Magnifier</kbd>', 'מגדיל בלי לגעת בטבעת. כל לחיצה במרכז הגלגל משנה את ההגדלה.', 'MENU → Focus → Focus Assistant'],
          ['<kbd>Initial Focus Mag.</kbd>', 'הגדלה ראשונית: x1.0 או x6.9 בפול-פריים.', 'MENU → Focus → Focus Assistant'],
          ['מרחק פוקוס במסך', 'כשמסובבים את הטבעת מופיע סרגל מרחק. לפי המדריך זה ערך להתייחסות בלבד.', 'אוטומטי'],
        ] },
        { t: 'h', text: 'DMF ו-Full Time DMF' },
        { t: 'p', html: '<kbd>DMF</kbd>: לחצו חצי, המצלמה ממקדת, ו<b>בלי לשחרר</b> מסובבים את טבעת הפוקוס לתיקון עדין. מושלם לפרחים: AF מגיע קרוב, אתם מחליטים על איזה עלה כותרת. <kbd>Full Time DMF</kbd> (MENU → Focus → AF/MF) מאפשר את זה בכל מצב AF.' },
        { t: 'h', text: 'כפתור Focus Hold בעדשה' },
        { t: 'p', html: 'הכפתור העגול בצד העדשה מבצע <kbd>Focus Hold</kbd>: כל עוד הוא לחוץ, הפוקוס נעול. שימושי ב-AF-C כשמשהו עובר לפני הנושא. אפשר לשייך לו פונקציה אחרת דרך <kbd>Custom Key/Dial Set.</kbd>.' },
        { t: 'sim', scene: 'night', preset: { mode: 'A', focal: 50, N: 2.8, lensAFMF: 'MF', peaking: true, tripod: true },
          task: { text: 'מתג העדשה על MF. סובבו את טבעת הפוקוס עד שה-Peaking (קווים אדומים) מופיע על הפנס הקרוב, וצלמו.', checks: [
            { t: 'פוקוס ידני', c: 'focusMode==MF' }, { t: 'חשיפה תקינה', c: 'expOk' } ] },
          hint: 'סיבוב הטבעת מפעיל את ההגדלה האוטומטית לכמה שניות. לחיצה על מרכז הגלגל מחליפה רמת הגדלה.' },
        { t: 'quiz', q: 'במצלמה Focus Mode הוא AF-C, אבל מתג AF/MF בעדשה על MF. מה יקרה?', options: ['AF-C יעבוד כרגיל', 'הפוקוס יהיה ידני, כי מתג העדשה גובר', 'המצלמה תציג שגיאה', 'יעבוד DMF'], answer: 1,
          explain: 'לפי המדריך, כשיש לעדשה מתג AF/MF, מצב המתג בעדשה מקבל עדיפות.' },
      ],
    },
  ],
};
