// Chapter 6 — colour, look and files. Facts: Sony Help Guide ILCE-7CM2 (docs/manuals)
export default {
  id: 'ch6', num: 6, title: 'צבע, מראה וקבצים', subtitle: 'איזון לבן, Creative Look, ו-RAW מול JPEG/HEIF',
  lessons: [
    {
      id: '6-1', title: 'איזון לבן: למה לבן יוצא כתום או כחול', minutes: 9,
      goal: 'לגרום ללבן להיראות לבן, או לבחור בכוונה אווירה חמה או קרה.',
      blocks: [
        { t: 'p', html: 'לכל מקור אור יש צבע, שנמדד ב<b>קלווין (K)</b>: נורת להט כ-3,000K (כתומה), שמש בצהריים כ-5,500K, צל כחלחל מעל 7,000K. העין מתרגלת ולא שמה לב, אבל המצלמה רושמת בדיוק מה שיש. <kbd>White Balance</kbd> אומר למצלמה מה צריך להיראות לבן.' },
        { t: 'diagram', kind: 'wb' },
        { t: 'table', head: ['הגדרה', 'מתי'], rows: [
          ['<kbd>Auto</kbd> (AWB)', 'ברוב המקרים. אפשר לכוון את ההעדפה ב-Priority Set in AWB.'],
          ['<kbd>Daylight</kbd>', 'שמש ישירה. שומר על השקיעה כתומה כמו שהיא.'],
          ['<kbd>Shade</kbd> / <kbd>Cloudy</kbd>', 'צל או עננים: מחמם את הכחלחלות.'],
          ['<kbd>Incandescent</kbd>', 'נורות להט ופנסי רחוב חמים.'],
          ['<kbd>Fluor.: Warm White / Cool White / Day White / Daylight</kbd>', 'ארבעה סוגי פלורסנט.'],
          ['<kbd>Flash</kbd>', 'מבזק (רק בסטילס).'],
          ['<kbd>Underwater Auto</kbd>', 'מתחת למים.'],
          ['<kbd>C.Temp./Filter</kbd>', 'בוחרים מספר קלווין בעצמכם, עם Rear dial L או R.'],
          ['<kbd>Custom 1/2/3</kbd>', 'מודדים לבן אמיתי בזירה ושומרים (עד 3 הגדרות).'],
        ] },
        { t: 'parts', view: 'rear', show: ['c1'], caption: 'כפתור C1 ליד MENU: בברירת המחדל הוא פותח את White Balance.' },
        { t: 'menu', path: ['MENU', 'Exposure/Color', 'White Balance', 'White Balance'], value: 'Auto', note: 'ב-Intelligent Auto ו-Scene Selection נעול על Auto.' },
        { t: 'menu', path: ['MENU', 'Exposure/Color', 'White Balance', 'Priority Set in AWB'], value: 'Standard / Ambience / White', note: 'Ambience משאיר חום של נורות, White מנטרל אותו.' },
        { t: 'h', text: 'Custom WB: הכי מדויק' },
        { t: 'steps', items: [
          'MENU → Exposure/Color → White Balance → White Balance → <kbd>Custom 1</kbd> → לחיצה ימינה בגלגל.',
          'בחרו את סמל הקליטה ולחצו במרכז הגלגל.',
          'כוונו את המצלמה כך שדף לבן (או כרטיס אפור) ממלא את מסגרת הקליטה, ולחצו במרכז.',
          'יופיע <i>Captured the custom WB data.</i> והערכים. לחצו שוב במרכז לשמירה.',
        ] },
        { t: 'sim', scene: 'night', preset: { mode: 'A', focal: 35, wb: 'Daylight' },
          task: { text: 'ב-Daylight הכיכר כתומה מאוד. החליפו ל-Incandescent (כפתור C1) וצלמו: הקירות יחזרו לצבע הטבעי שלהם.', checks: [
            { t: 'Incandescent', c: 'wb==Incandescent' }, { t: 'חשיפה תקינה', c: 'expOk' } ] },
          hint: 'אחר כך נסו AWB. ב-Standard הוא משאיר מעט חום כדי שהלילה ירגיש כמו לילה.' },
        { t: 'tip', html: 'אם מצלמים ב-RAW, אפשר לשנות איזון לבן אחר כך בלי פגיעה באיכות. ב-JPEG/HEIF הצבע "נאפה" לתוך הקובץ.' },
        { t: 'quiz', q: 'צילמתם חתונה באולם עם נורות להט, והעור יוצא כתום מדי גם ב-AWB. מה הצעד הכי מדויק?', options: ['Shade', 'Custom WB על דף לבן באולם', 'Daylight', 'להעלות ISO'], answer: 1,
          explain: 'Custom WB מודד את האור האמיתי בזירה. Shade ו-Daylight דווקא יחממו עוד.' },
      ],
    },
    {
      id: '6-2', title: 'Creative Look: המראה של התמונה', minutes: 9,
      goal: 'לבחור מראה מוכן ולכוונן אותו, כך שה-JPEG יוצא מהמצלמה כמו שרציתם.',
      blocks: [
        { t: 'p', html: '<kbd>Creative Look</kbd> הוא "מתכון" לצבע, ניגודיות וחדות שהמצלמה מחילה על JPEG ו-HEIF. יש 10 מראות מוכנים, וכל אחד ניתן לכוונון.' },
        { t: 'table', head: ['Look', 'אופי', 'מתאים ל-'], rows: [
          ['<kbd>ST</kbd> Standard', 'מאוזן', 'ברירת מחדל לכל דבר'],
          ['<kbd>PT</kbd> Portrait', 'עור רך ונעים', 'פורטרט'],
          ['<kbd>NT</kbd> Neutral', 'רווייה וחדות נמוכות', 'עריכה אחר כך'],
          ['<kbd>VV</kbd> Vivid', 'רווייה וניגודיות גבוהות', 'פרחים, ים, ירוק אביבי'],
          ['<kbd>VV2</kbd> Vivid 2', 'צבעים בהירים וחיים עם בהירות (Clarity)', 'נוף, טיולים'],
          ['<kbd>FL</kbd> Film', 'צבע רגוע עם ניגודיות חדה, מראה "קולנועי"', 'רחוב, אווירה'],
          ['<kbd>IN</kbd> Instant', 'מט, ניגודיות ורווייה מופחתות', 'מראה רטרו'],
          ['<kbd>SH</kbd> Soft Highkey', 'בהיר, שקוף, רך', 'אור בוקר, אנשים, מינימליזם'],
          ['<kbd>BW</kbd> Black & White', 'שחור-לבן', 'מבנה, צללים, דרמה'],
          ['<kbd>SE</kbd> Sepia', 'גוון ספיה מונוכרומטי', 'נוסטלגיה'],
        ] },
        { t: 'menu', path: ['MENU', 'Exposure/Color', 'Color/Tone', 'Creative Look'], value: 'ST' },
        { t: 'h', text: 'שמונה פרמטרים לכוונון' },
        { t: 'table', head: ['פרמטר', 'טווח', 'מה הוא עושה'], rows: [
          ['Contrast', '−9 עד +9', 'הפרש בין אור לצל'], ['Highlights', '−9 עד +9', 'בהירות האזורים הבהירים'],
          ['Shadows', '−9 עד +9', 'בהירות האזורים הכהים'], ['Fade', '0 עד 9', 'שחורים "דהויים"'],
          ['Saturation', '−9 עד +9', 'עוצמת הצבע'], ['Sharpness', '0 עד 9', 'הדגשת קווי מתאר'],
          ['Sharpness Range', '1 עד 5', 'על כמה עדינים הקווים שמחודדים'], ['Clarity', '0 עד 9', 'ניגודיות מקומית בפרטים'],
        ] },
        { t: 'tip', html: 'כששיניתם פרמטר מברירת המחדל, מופיעה כוכבית ליד סמל ה-Look במסך. לאיפוס: כפתור Delete במסך הכוונון. אפשר לשמור עד 6 מתכונים אישיים ב-<kbd>Custom Look</kbd>.' },
        { t: 'sim', scene: 'kyoto', preset: { mode: 'A', N: 2.8, look: 'ST' },
          task: { text: 'צלמו את הפורטרט שלוש פעמים: PT, FL ו-BW (כפתור Fn → Creative Look). סיימו בשחור-לבן.', checks: [
            { t: 'Look = BW', c: 'look==BW' }, { t: 'העין חדה', c: 'eyeSharp' }, { t: 'חשיפה תקינה', c: 'expOk' } ] } },
        { t: 'quiz', q: 'אתם מתכננים לערוך כל תמונה במחשב, אבל מצלמים ב-JPEG. איזה Look ישמור הכי הרבה מקום לעריכה?', options: ['VV', 'NT', 'FL', 'SH'], answer: 1,
          explain: 'לפי המדריך, NT מוריד רווייה וחדות ומתאים לחומר שיעובד במחשב. עדיף עוד יותר: RAW.' },
      ],
    },
    {
      id: '6-3', title: 'RAW, JPEG ו-HEIF', minutes: 9,
      goal: 'לבחור פורמט קובץ שמתאים לאיך שאתם עובדים, ולהבין מה כל אפשרות שומרת.',
      blocks: [
        { t: 'p', html: '<b>RAW</b> הוא הנתונים של החיישן לפני עיבוד, 14 ביט לפיקסל. <b>JPEG</b> ו-<b>HEIF</b> הם תמונות מוכנות שהמצלמה כבר עיבדה: איזון לבן, Creative Look, DRO, הפחתת רעש.' },
        { t: 'table', head: ['פורמט', 'יתרון', 'חיסרון'], rows: [
          ['<kbd>RAW</kbd>', 'גמישות מקסימלית: חשיפה, איזון לבן, צללים', 'קבצים גדולים, חייבים לעבד (Imaging Edge Desktop או תוכנה אחרת)'],
          ['<kbd>RAW & JPEG</kbd> / <kbd>RAW & HEIF</kbd>', 'גם קובץ לשיתוף וגם גיבוי לעריכה', 'הכי הרבה מקום בכרטיס'],
          ['<kbd>JPEG</kbd>', 'נפתח בכל מקום', '8 ביט, פחות מרווח לתיקונים'],
          ['<kbd>HEIF</kbd> (4:2:0 / 4:2:2)', 'איכות גבוהה וקבצים קטנים', 'לא כל מחשב ותוכנה פותחים'],
        ] },
        { t: 'menu', path: ['MENU', 'Shooting', 'Image Quality/Rec', 'File Format'], value: 'RAW / RAW & JPEG / JPEG' },
        { t: 'menu', path: ['MENU', 'Shooting', 'Image Quality/Rec', 'JPEG/HEIF Switch'], value: 'JPEG / HEIF(4:2:0) / HEIF(4:2:2)' },
        { t: 'menu', path: ['MENU', 'Shooting', 'Image Quality/Rec', 'RAW File Type'], value: 'Uncompressed / Lossless Comp (L/M/S) / Compressed', note: 'Compressed בצילום רצף: 12 ביט במקום 14.' },
        { t: 'table', head: ['JPEG Image Size (3:2)', 'פיקסלים'], rows: [['L: 33M', '7008×4672'], ['M: 14M', '4608×3072'], ['S: 8.2M', '3504×2336']] },
        { t: 'p', html: '<kbd>JPEG Quality</kbd>: Extra fine / Fine / Standard / Light. <kbd>Aspect Ratio</kbd>: 3:2 (כמו פילם 35 מ"מ), 4:3, 16:9, 1:1. קובץ RAW תמיד 3:2. ה-JPEG שנשמר לצידו מקבל את היחס שבחרתם.' },
        { t: 'recipe', title: 'המלצה למתחילים', items: [['File Format', 'RAW & JPEG'], ['RAW File Type', 'Lossless Comp (L)'], ['JPEG Quality', 'Fine'], ['Aspect Ratio', '3:2']] },
        { t: 'warn', html: 'Soft Skin Effect ו-Creative Look לא נשמרים ב-RAW עצמו. ב-RAW רואים אותם רק בתצוגה ובתוכנות של סוני.' },
        { t: 'quiz', q: 'מה ההבדל בין Lossless Comp ל-Compressed ב-RAW?', options: ['אין הבדל', 'Lossless קטן יותר בלי לאבד איכות; Compressed בערך חצי מגודל Uncompressed', 'Compressed הוא JPEG', 'Lossless הוא רק לווידאו'], answer: 1,
          explain: 'Lossless Comp דוחס בלי לפגוע באיכות. Compressed קטן בערך פי שניים מ-Uncompressed, ובצילום רצף הוא יורד ל-12 ביט.' },
      ],
    },
    {
      id: '6-4', title: 'Picture Profile ו-Soft Skin בקצרה', minutes: 5,
      goal: 'לדעת שהכלים האלה קיימים, ומתי לא לגעת בהם בסטילס.',
      blocks: [
        { t: 'p', html: '<kbd>Picture Profile</kbd> נועד בעיקר לווידאו (כך נכתב במדריך). יש פרופילים מוכנים <kbd>PP1</kbd> עד <kbd>PP11</kbd>, כמו Cine1/2, HLG2 ו-<kbd>S-Cinetone</kbd> (PP11), וגם S-Log3 לעבודה מקצועית עם צבע. נרחיב בפרק הווידאו.' },
        { t: 'menu', path: ['MENU', 'Exposure/Color', 'Color/Tone', 'Picture Profile'], value: 'Off', note: 'כש-Picture Profile פעיל, DRO נעול על Off.' },
        { t: 'warn', html: 'מתחילים בסטילס: השאירו Picture Profile על <b>Off</b> ושלטו במראה עם Creative Look. פרופיל כמו S-Log3 נראה שטוח ואפור עד שמעבדים אותו.' },
        { t: 'p', html: '<kbd>Soft Skin Effect</kbd> מחליק עור כשהמצלמה מזהה פנים: Off, או On ברמות High / Mid / Low. הוא לא זמין כשהקובץ RAW בלבד, ולא בזום דיגיטלי.' },
        { t: 'menu', path: ['MENU', 'Exposure/Color', 'Color/Tone', 'Soft Skin Effect'], value: 'On: Low' },
        { t: 'parts', view: 'rear', show: ['fn'], caption: 'אפשר להוסיף Soft Skin Effect ו-Creative Look לתפריט Fn כדי להגיע אליהם מהר.' },
        { t: 'tip', html: 'פורטרט עדין: Creative Look <kbd>PT</kbd> ו-Soft Skin <kbd>Low</kbd>. רמה High מורגשת מהר ונראית מלאכותית.' },
        { t: 'quiz', q: 'בחרתם Picture Profile PP11 ושמתם לב שאי אפשר לשנות DRO. למה?', options: ['תקלה', 'כש-Picture Profile פעיל, DRO נעול על Off', 'צריך RAW', 'צריך עדשה אחרת'], answer: 1,
          explain: 'לפי המדריך, D-Range Optimizer נעול על Off כש-Picture Profile מוגדר לכל ערך חוץ מ-Off.' },
      ],
    },
  ],
};
