export default {
  id: 'ch9', num: 9, title: 'התאמה אישית',
  subtitle: 'להפוך את המצלמה לשלכם: Fn, כפתורים, חוגות וזיכרונות 1/2/3',
  lessons: [
    {
      id: '9-1', title: 'תפריט Fn: 12 קיצורי הדרך שלכם', minutes: 7,
      goal: 'לפתוח את תפריט Fn, לשנות בו הגדרות במהירות, ולבנות אותו מחדש לפי מה שאתם באמת משנים.',
      blocks: [
        { t: 'p', html: 'כפתור <kbd>Fn</kbd> פותח בתחתית המסך רשת של 12 הגדרות שמשנים הכי הרבה, כמו Drive Mode ו-Focus Mode. זו הדרך המהירה ביותר לשנות משהו בלי להיכנס ל-MENU.' },
        { t: 'parts', view: 'rear', show: ['fn', 'control-wheel', 'wheel-center'], caption: 'Fn פותח את הרשת. הגלגל מזיז בין המשבצות, החוגה הקדמית משנה את הערך, ולחיצה במרכז הגלגל מאשרת.' },
        { t: 'steps', items: [
          'לחצו <kbd>DISP</kbd> עד שהמסך לא נמצא במצב <kbd>For viewfinder</kbd>.',
          'לחצו <kbd>Fn</kbd>.',
          'בחרו משבצת עם למעלה/למטה/ימין/שמאל של הגלגל.',
          'סובבו את החוגה הקדמית לשינוי הערך. חלק מההגדרות מתכווננות גם ב-Rear dial L או R.',
          'מגע: אפשר גם להחליק כלפי מעלה על המסך כדי לפתוח את התפריט.',
        ] },
        { t: 'menu', path: ['MENU', 'Setup', 'Operation Customize', 'Fn Menu Settings'], value: '12 פריטים לסטילס + 12 לווידאו', note: 'לחיצה ארוכה על אייקון בתפריט Fn פותחת את ההגדרה הזו ישירות (כשהמגע מופעל).' },
        { t: 'recipe', title: 'הצעה ל-12 משבצות (סטילס)', items: [
          ['שורה עליונה', 'Drive Mode · Focus Mode · Focus Area · Exposure Comp. · ISO · Recognition Target'],
          ['שורה תחתונה', 'Metering Mode · White Balance · D-Range Optimizer · Creative Look · File Format · SteadyShot'],
        ] },
        { t: 'tip', html: 'אל תשכפלו ב-Fn מה שכבר יש לו כפתור. ISO יושב על צד ימין של הגלגל, ואיזון לבן על <kbd>C1</kbd> כברירת מחדל. את המשבצות שמתפנות תנו ל-<kbd>Shutter Type</kbd> או ל-<kbd>Silent Mode</kbd>.' },
        { t: 'quiz', q: 'כמה פריטים אפשר לשים בתפריט Fn לצילום סטילס?', options: ['6', '8', '12', '24'], answer: 2, explain: '12 לסטילס ו-12 נפרדים לווידאו.' },
      ],
    },
    {
      id: '9-2', title: 'Custom Key/Dial Set.: כל כפתור עושה מה שתרצו', minutes: 10,
      goal: 'להכיר את 9 הכפתורים והחוגות שאפשר לתכנת, ואת My Dial Settings להחלפה זמנית של תפקידי החוגות.',
      blocks: [
        { t: 'p', html: 'כמעט כל כפתור במצלמה ניתן לתכנות, בנפרד לסטילס, לווידאו ולצפייה. אלה הפקדים שניתנים להגדרה:' },
        { t: 'table', head: ['פקד', 'ברירת מחדל ידועה'], rows: [
          ['<kbd>C1</kbd> (Custom Button 1)', 'White Balance'], ['<kbd>C2</kbd> (Custom Button 2)', 'ניתן להגדרה'],
          ['<kbd>AF-ON</kbd>', 'Tracking On + AF On'], ['<kbd>Rear dial R</kbd>', 'Exposure Comp.'],
          ['<kbd>Rear dial L</kbd>, <kbd>Front dial</kbd>', 'צמצם / תריס לפי המצב'], ['<kbd>MOVIE</kbd>', 'הקלטה'],
          ['<kbd>Fn</kbd>', 'תפריט Fn'], ['<kbd>Control Wheel</kbd> + מרכז + שמאל/ימין/למטה', 'Drive, ISO, Image Index…'],
        ] },
        { t: 'parts', view: 'rear', show: ['c1', 'c2', 'af-on', 'rear-dial-l', 'wheel-center'] },
        { t: 'menu', path: ['MENU', 'Setup', 'Operation Customize', 'Custom Key/Dial Set.'], value: 'בחירת כפתור → בחירת פונקציה' },
        { t: 'h', text: 'כפתור Focus Hold על העדשה' },
        { t: 'parts', view: 'lens', show: ['focus-hold', 'afmf-switch'], caption: 'הכפתור העגול בצד העדשה. כברירת מחדל הוא עוצר את ה-AF ונועל את מרחק הפוקוס כל עוד מחזיקים אותו.' },
        { t: 'p', html: 'גם את <kbd>Focus Hold</kbd> שעל העדשה אפשר לתכנת מתוך אותו מסך Custom Key. דוגמאות: <kbd>Eye AF</kbd>, <kbd>Aperture Preview</kbd>, או החלפה בין מצבי Recognition Target. הכפתור נוח לאגודל של יד שמאל, שתומכת בעדשה.' },
        { t: 'h', text: 'My Dial Settings' },
        { t: 'p', html: 'אפשר לשמור עד 3 "חבילות" של תפקידים לחוגה הקדמית, ל-Rear dial L, ל-Rear dial R ולגלגל (<kbd>My Dial 1</kbd>–<kbd>3</kbd>), ולהפעיל אותן מכפתור. ההפעלה יכולה להיות כל עוד מחזיקים (<kbd>during Hold</kbd>), במחזור <kbd>1→2→3</kbd>, או כמתג (<kbd>Toggle</kbd>).' },
        { t: 'menu', path: ['MENU', 'Setup', 'Dial Customize', 'My Dial Settings'], value: 'My Dial 1 / 2 / 3' },
        { t: 'pro', html: 'הגדרה פופולרית: <b>Back-button focus</b>. ב-<kbd>AF w/ Shutter</kbd> בוחרים Off, ואז רק AF-ON ממקד. כך אפשר לנעול פוקוס פעם אחת ולצלם הרבה בלי שכפתור הצילום ימקד מחדש.' },
        { t: 'quiz', q: 'איזה פקד אינו ברשימת הפקדים שניתנים לתכנות ב-Custom Key/Dial Set.?', options: ['C2', 'Rear dial R', 'כפתור MENU', 'MOVIE'], answer: 2, explain: 'הרשימה הרשמית כוללת C1, C2, Rear dial L/R, MOVIE, AF-ON, Fn, הגלגל וכפתוריו והחוגה הקדמית. כפתור MENU לא ברשימה.' },
      ],
    },
    {
      id: '9-3', title: 'זיכרונות 1/2/3 בגלגל המצבים', minutes: 9,
      goal: 'לשמור שלוש "מצלמות מוכנות" ולעבור ביניהן בסיבוב אחד של גלגל המצבים.',
      blocks: [
        { t: 'p', html: 'בגלגל המצבים יש <kbd>1</kbd>, <kbd>2</kbd> ו-<kbd>3</kbd>. כל אחד מהם זוכר חבילה שלמה של הגדרות: מצב חשיפה, צמצם, תריס, ISO, פוקוס, WB, Look ועוד. אפשר לשמור עוד 4 (M1–M4) על כרטיס הזיכרון.' },
        { t: 'parts', view: 'top', show: ['mode-dial', 'sq-dial'], caption: 'הזיכרונות נשמרים בנפרד לכל מצב בגלגל Still/Movie/S&Q.' },
        { t: 'steps', items: [
          'כוונו את המצלמה בדיוק כמו שאתם רוצים.',
          '<kbd>MENU</kbd> → <kbd>Shooting</kbd> → <kbd>Shooting Mode</kbd> → <kbd>Camera Set. Memory</kbd> → מספר.',
          'לחיצה במרכז הגלגל לאישור.',
          'מעכשיו: גלגל המצבים על אותו מספר מחזיר את כל ההגדרות (<kbd>Recall Camera Setting</kbd>).',
        ] },
        { t: 'recipe', title: '1 · פורטרט', items: [['מצב', 'A, ‏F2.8'], ['ISO', 'AUTO'], ['פוקוס', 'AF-C, Wide, Human'], ['Look', 'PT'], ['Drive', 'Cont. Lo']] },
        { t: 'recipe', title: '2 · נוף על חצובה', items: [['מצב', 'A, ‏F8'], ['ISO', '100'], ['פוקוס', 'AF-S, Spot: M'], ['SteadyShot', 'Off'], ['Drive', 'Self-timer 2 sec'], ['קובץ', 'RAW']] },
        { t: 'recipe', title: '3 · רחוב ולילה', items: [['מצב', 'A, ‏F2.8–F4'], ['ISO', 'AUTO (Min. SS: FAST)'], ['פוקוס', 'AF-C, Zone'], ['WB', 'AWB'], ['Shutter Type', 'Electronic, Silent On']] },
        { t: 'warn', html: '<kbd>Program Shift</kbd> לא נשמר בזיכרון. כדי לשנות זיכרון קיים, משנים את ההגדרות ושומרים שוב לאותו מספר.' },
        { t: 'quiz', q: 'כמה זיכרונות נשמרים במצלמה עצמה לכל מצב צילום?', options: ['1', '3', '4', '10'], answer: 1, explain: '3 בגוף (1/2/3 בגלגל) ועוד עד 4 (M1–M4) על הכרטיס.' },
      ],
    },
    {
      id: '9-4', title: 'My Menu והגדרות Setup שכדאי להכיר', minutes: 7,
      goal: 'לבנות תפריט אישי של עד 42 פריטים, ולכוון כמה הגדרות שמשנות את החוויה היומיומית.',
      blocks: [
        { t: 'menu', path: ['MENU', 'My Menu', 'My Menu Setting', 'Add Item'], value: 'עד 42 פריטים' },
        { t: 'tip', html: 'קיצור: כשהסמן עומד על פריט בכל תפריט, לחצו על כפתור המחיקה (<kbd>C2</kbd>) ובחרו <kbd>Add to My Menu</kbd>.' },
        { t: 'parts', view: 'rear', show: ['menu', 'c2'] },
        { t: 'table', head: ['הגדרה', 'נתיב', 'למה'], rows: [
          ['<kbd>Auto Review</kbd>', 'Setup → Display Option', 'הצגת התמונה מיד אחרי הצילום: Off / 2 / 5 / 10 שניות'],
          ['<kbd>Grid Line Display</kbd>', 'Shooting → Shooting Display', 'קווי שלישים לקומפוזיציה'],
          ['<kbd>Anti-dust Function</kbd>', 'Setup', 'ניקוי חיישן, וסגירת תריס בכיבוי'],
          ['<kbd>Format</kbd>', 'Shooting → Media', 'אתחול כרטיס במצלמה (מוחק הכל)'],
          ['<kbd>Bluetooth Rmt Ctrl</kbd>', 'Network', 'שלט Bluetooth לצילום בלי לגעת במצלמה'],
          ['<kbd>Dial / Wheel Lock</kbd>', 'Setup → Dial Customize', 'נעילת חוגות: מחזיקים Fn עד שמופיע Locked.'],
        ] },
        { t: 'tip', html: 'לפני מסע ארוך: Format לכרטיס במצלמה (לא במחשב), סוללה טעונה, ובדיקה ש-1/2/3 שמורים.' },
        { t: 'quiz', q: 'מה הדרך המהירה להוסיף פריט ל-My Menu?', options: ['לחיצה ארוכה על MENU', 'כפתור המחיקה כשהסמן על הפריט → Add to My Menu', 'Fn + MOVIE', 'אי אפשר'], answer: 1, explain: 'כשהסמן על פריט בתפריט, כפתור המחיקה פותח תפריט הקשר עם Add to My Menu.' },
      ],
    },
  ],
};
