// Every physical control of the α7C II and the FE 24-50mm F2.8 G.
// x,y are positions on the matching figure (0..1 of its width/height). Names follow the Sony Help Guide.
export const PARTS = {
  /* ---------- top ---------- */
  'shutter': { view: 'top', x: 0.818, y: 0.10, r: 0.045, en: 'Shutter button', he: 'כפתור הצילום',
    d: 'לחיצה חצי עד הסוף מפעילה פוקוס ומדידת אור; לחיצה מלאה מצלמת. זה הכפתור החשוב ביותר במצלמה.' },
  'power': { view: 'top', x: 0.89, y: 0.17, r: 0.03, en: 'ON/OFF (Power) switch', he: 'מתג הפעלה',
    d: 'טבעת סביב כפתור הצילום: ON / OFF. אפשר להדליק ולכבות בלי להוריד את העין מהעינית.' },
  'mode-dial': { view: 'top', x: 0.69, y: 0.42, r: 0.075, en: 'Mode dial', he: 'גלגל המצבים',
    d: 'AUTO, P, A, S, M ושלושה זיכרונות 1/2/3. קובע מי מחליט על הצמצם והתריס: אתם או המצלמה.' },
  'sq-dial': { view: 'top', x: 0.705, y: 0.665, r: 0.04, en: 'Still/Movie/S&Q dial', he: 'בורר תמונה / וידאו / S&Q',
    d: 'הטבעת שמתחת לגלגל המצבים (עם הלשונית). מצלמה = סטילס, מצלמת וידאו = וידאו, S&Q = הילוך איטי/מהיר.' },
  'movie': { view: 'top', x: 0.885, y: 0.34, r: 0.03, en: 'MOVIE (Movie) button', he: 'כפתור הקלטת וידאו',
    d: 'הכפתור עם הטבעת האדומה. מתחיל ועוצר הקלטה. אפשר לשנות לו את התפקיד.' },
  'rear-dial-r': { view: 'top', x: 0.905, y: 0.62, r: 0.06, en: 'Rear dial R', he: 'חוגה אחורית R',
    d: 'החוגה הגדולה בפינה (במקום חוגת פיצוי החשיפה של הדגם הקודם). כברירת מחדל: פיצוי חשיפה.' },
  'shoe': { view: 'top', x: 0.42, y: 0.55, r: 0.06, en: 'Multi Interface Shoe', he: 'נעל אביזרים',
    d: 'לפלאש חיצוני, מיקרופון או אביזרים. הכיסוי השחור נשלף.' },
  'sensor-mark': { view: 'top', x: 0.305, y: 0.415, r: 0.025, en: 'Image sensor position mark', he: 'סימון מיקום החיישן',
    d: 'הקו האופקי מסמן את מישור החיישן. מרחק הפוקוס המינימלי של העדשה (0.19 מ\' ב-24 מ"מ) נמדד מכאן, לא מקצה העדשה.' },
  'speaker': { view: 'top', x: 0.185, y: 0.375, r: 0.03, en: 'Speaker', he: 'רמקול', d: 'לצלילי פוקוס וצפייה בווידאו.' },
  'top-label': { view: 'top', x: 0.12, y: 0.575, r: 0.04, en: 'Model name', he: 'שם הדגם', d: 'α7C II (ILCE-7CM2).' },
  'menu-top': { view: 'top', x: 0.525, y: 0.9, r: 0.035, en: 'MENU button', he: 'כפתור MENU', d: 'פותח את התפריט הראשי.' },

  /* ---------- rear ---------- */
  'evf': { view: 'rear', x: 0.128, y: 0.188, r: 0.07, en: 'Viewfinder', he: 'עינית (EVF)',
    d: 'עינית אלקטרונית 0.70×, 2.36 מיליון נקודות. מראה בדיוק את התמונה שתצא, כולל חשיפה וצבע.' },
  'eye-sensor': { view: 'rear', x: 0.222, y: 0.199, r: 0.022, en: 'Eye sensor', he: 'חיישן עין',
    d: 'כשמקרבים את העין המסך כבה והעינית נדלקת אוטומטית.' },
  'diopter': { view: 'rear', x: 0.29, y: 0.214, r: 0.03, en: 'Diopter-adjustment dial', he: 'גלגל דיופטר',
    d: 'מתאים את העינית לראייה שלכם. סובבו עד שהטקסט בעינית חד, פעם אחת וזהו.' },
  'monitor': { view: 'rear', x: 0.40, y: 0.66, r: 0.12, en: 'Monitor (touch panel)', he: 'מסך מגע מתהפך',
    d: '3 אינץ\', נפתח הצידה (176°) ומסתובב (270°). מגע לבחירת פוקוס, להגדלה ולתפריטים.' },
  'menu': { view: 'rear', x: 0.535, y: 0.185, r: 0.035, en: 'MENU button', he: 'כפתור MENU',
    d: 'כל ההגדרות של המצלמה. הלשוניות: Main, Shooting, Exposure/Color, Focus, Playback, Network, Setup, My Menu.' },
  'c1': { view: 'rear', x: 0.635, y: 0.185, r: 0.03, en: 'C1 button (Custom button 1)', he: 'כפתור C1',
    d: 'כפתור מותאם אישית. ברירת מחדל: איזון לבן (White Balance).' },
  'rear-dial-l': { view: 'rear', x: 0.775, y: 0.18, r: 0.05, en: 'Rear dial L', he: 'חוגה אחורית L',
    d: 'החוגה האופקית מתחת לאגודל. ב-A משנה צמצם, ב-S תריס, ב-M תריס (והחוגה הקדמית צמצם).' },
  'af-on': { view: 'rear', x: 0.775, y: 0.335, r: 0.035, en: 'AF-ON (AF On) button', he: 'כפתור AF-ON',
    d: 'מפעיל פוקוס בלי לגעת בכפתור הצילום. ברירת מחדל: Tracking On + AF On. בצפייה: הגדלה.' },
  'fn': { view: 'rear', x: 0.77, y: 0.49, r: 0.03, en: 'Fn (Function) button', he: 'כפתור Fn',
    d: 'תפריט מהיר של 12 הגדרות נפוצות (פוקוס, ISO, איזון לבן...). בצפייה: שליחה לסמארטפון.' },
  'control-wheel': { view: 'rear', x: 0.85, y: 0.684, r: 0.075, en: 'Control wheel', he: 'גלגל השליטה',
    d: 'מסתובב וגם נלחץ ב-4 כיוונים ובמרכז. ניווט בתפריטים וגישה ישירה ל-DISP, ISO, Drive ו-Index.' },
  'wheel-disp': { view: 'rear', x: 0.85, y: 0.548, r: 0.025, en: 'DISP (top)', he: 'DISP — למעלה',
    d: 'מחליף את תצוגת המידע במסך (היסטוגרמה, פלס, תצוגה נקייה).' },
  'wheel-iso': { view: 'rear', x: 0.931, y: 0.695, r: 0.025, en: 'ISO (right)', he: 'ISO — ימין', d: 'בחירת רגישות ISO.' },
  'wheel-drive': { view: 'rear', x: 0.733, y: 0.695, r: 0.025, en: 'Drive Mode / Self-timer (left)', he: 'Drive — שמאל',
    d: 'תמונה בודדת, רצף, טיימר, Bracket.' },
  'wheel-index': { view: 'rear', x: 0.841, y: 0.857, r: 0.022, en: 'Image Index (bottom)', he: 'למטה',
    d: 'בצפייה: תצוגת אינדקס של תמונות. בצילום ניתן להגדרה.' },
  'wheel-center': { view: 'rear', x: 0.85, y: 0.684, r: 0.022, en: 'Center button', he: 'כפתור מרכזי', d: 'אישור בחירה. בצילום ניתן להגדרה (למשל Focus Magnifier).' },
  'c2': { view: 'rear', x: 0.881, y: 0.897, r: 0.03, en: 'C2 button / Delete', he: 'כפתור C2 / מחיקה',
    d: 'בצילום: כפתור מותאם אישית 2. בצפייה: מחיקת תמונה.' },
  'playback': { view: 'rear', x: 0.7925, y: 0.899, r: 0.03, en: 'Playback button', he: 'כפתור צפייה', d: 'הצגת התמונות שצילמתם.' },
  'grip-rear': { view: 'rear', x: 0.93, y: 0.38, r: 0.04, en: 'Thumb rest', he: 'משענת אגודל', d: 'המקום של האגודל הימני באחיזה.' },

  /* ---------- front ---------- */
  'front-dial': { view: 'front', x: 0.115, y: 0.28, r: 0.055, en: 'Front dial', he: 'חוגה קדמית',
    d: 'מתחת לכפתור הצילום, מתסובבת עם האצבע המורה. ב-A/M משנה צמצם; ב-S תריס; ב-P מזיזה את Program Shift.' },
  'shutter-front': { view: 'front', x: 0.135, y: 0.12, r: 0.045, en: 'Shutter button', he: 'כפתור הצילום', d: 'חצי לחיצה = פוקוס, לחיצה מלאה = צילום.' },
  'af-illuminator': { view: 'front', x: 0.297, y: 0.29, r: 0.022, en: 'Self-timer lamp / AF illuminator', he: 'נורת טיימר / תאורת עזר לפוקוס',
    d: 'מהבהבת בזמן ספירת טיימר ומאירה לעזרה בפוקוס בחושך. אל תכסו אותה.' },
  'lens-release': { view: 'front', x: 0.36, y: 0.86, r: 0.03, en: 'Lens release button', he: 'כפתור שחרור העדשה',
    d: 'לחצו והחזיקו, וסובבו את העדשה נגד כיוון השעון (כשמסתכלים מקדימה) כדי להוציא אותה.' },
  'mount-index': { view: 'front', x: 0.722, y: 0.295, r: 0.022, en: 'Mounting index', he: 'סימון הרכבה',
    d: 'הנקודה הלבנה. מיישרים מולה את הנקודה הלבנה שעל העדשה, מכניסים ומסובבים עד קליק.' },
  'mount': { view: 'front', x: 0.6, y: 0.24, r: 0.04, en: 'E-mount', he: 'תושבת E',
    d: 'תושבת הכידון של Sony E. כל עדשות FE ו-E מתאימות (E מייצרות חיתוך APS-C).' },
  'sensor': { view: 'front', x: 0.6, y: 0.55, r: 0.1, en: 'Image sensor', he: 'חיישן התמונה',
    d: 'Full Frame 35.9×23.9 מ"מ, 33 מגה-פיקסל, BSI. לא נוגעים בו! ניקוי רק בנשיפה או ב-Sensor Cleaning.' },
  'lens-contacts': { view: 'front', x: 0.6, y: 0.88, r: 0.04, en: 'Lens contacts', he: 'מגעי העדשה', d: 'החיבור החשמלי לעדשה. לשמור נקיים ויבשים.' },
  'mic': { view: 'front', x: 0.475, y: 0.12, r: 0.025, en: 'Microphone', he: 'מיקרופון', d: 'סטריאו, שני חורים בחזית. לא לכסות בזמן הקלטה.' },
  'grip': { view: 'front', x: 0.12, y: 0.62, r: 0.06, en: 'Grip', he: 'ידית אחיזה', d: 'שלוש אצבעות על הידית, המורה על כפתור הצילום.' },
  'front-badge': { view: 'front', x: 0.875, y: 0.3, r: 0.035, en: 'α 7C', he: 'סמל הדגם', d: '' },

  /* ---------- lens (side view, front to the left) ---------- */
  'focus-ring': { view: 'lens', en: 'Focus ring', he: 'טבעת פוקוס',
    d: 'הטבעת המחורצת הקדמית. פעילה ב-MF וב-DMF. "Linear Response MF": כמה שמסובבים, ככה הפוקוס זז, בלי תלות במהירות.' },
  'zoom-ring': { view: 'lens', en: 'Zoom ring', he: 'טבעת זום',
    d: 'משנה אורך מוקד בין 24 ל-50 מ"מ. העדשה מתארכת בכ-2 ס"מ לכיוון 24 מ"מ.' },
  'zoom-scale': { view: 'lens', en: 'Focal length marks', he: 'סימוני אורך מוקד', d: '24 · 28 · 35 · 50 מול קו הסימון.' },
  'aperture-ring': { view: 'lens', en: 'Aperture ring', he: 'טבעת צמצם',
    d: 'A = המצלמה (או החוגה) קובעת את הצמצם. F2.8–F22 בקפיצות של 1/3 סטופ = הטבעת קובעת. אין נעילה (Iris Lock) בעדשה הזו.' },
  'afmf-switch': { view: 'lens', en: 'Focus mode switch (AF/MF)', he: 'מתג AF/MF',
    d: 'MF בעדשה גובר על כל הגדרה במצלמה. לפוקוס אוטומטי גם העדשה וגם המצלמה צריכות להיות על AF.' },
  'focus-hold': { view: 'lens', en: 'Focus hold button', he: 'כפתור Focus Hold',
    d: 'לחיצה בזמן AF נועלת את מרחק הפוקוס. ניתן לשייך לו פונקציה אחרת (למשל Eye AF) ב-Custom Key Setting.' },
  'click-switch': { view: 'lens', en: 'Aperture click switch', he: 'מתג קליקים לטבעת הצמצם',
    d: 'בתחתית העדשה. ON = קליק בכל שליש סטופ (סטילס). OFF = טבעת חלקה ושקטה (וידאו).' },
  'lens-index': { view: 'lens', en: 'Lens mounting index', he: 'נקודת ההרכבה בעדשה', d: 'מיישרים מול הנקודה הלבנה בגוף.' },
  'filter-thread': { view: 'lens', en: 'Filter thread Ø67 mm', he: 'הברגת פילטר 67 מ"מ',
    d: 'לא מסתובבת בזמן פוקוס, אז פילטר מקטב (CPL) שומר על הכיוון שלו.' },
  'hood-mount': { view: 'lens', en: 'Hood bayonet (ALC-SH178)', he: 'תושבת למגן אור',
    d: 'מגן אור בצורת עלי כותרת. מונע הבזקים ומגן על העדשה. אפשר להפוך אותו לאחסון.' },
  'g-badge': { view: 'lens', en: 'G lens badge', he: 'סמל G', d: 'סדרת G של Sony: אופטיקה איכותית, אטימות לאבק ולחות.' },
};

export const VIEWS = {
  top: { img: 'img/body-top.webp', ratio: 1600 / 644, he: 'מלמעלה' },
  rear: { img: 'img/body-rear.webp', ratio: 1600 / 957, he: 'מאחור', screen: { x: 0.113, y: 0.348, w: 0.578, h: 0.605 } },
  front: { img: 'img/body-front.webp', ratio: 1600 / 827, he: 'מקדימה (בלי עדשה)' },
  lens: { he: 'העדשה מהצד' },
};
